import Navbar from './ui/sections/Navbar'
import Footer from "./ui/sections/Footer"

import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-rows-[auto_1fr_auto]">
            <Navbar/>
                {children}
            <Footer/>
        </main>
      </body>
    </html>
  )
}
